### ISSUE TITLE
the Flesh and Demon enchantment dmg stacks infinitely

### ISSUE THREAD

**Issue by stellraz** [Fargowilta/Fargowiltas#109]
as the title says, they stack infinitely and after a while it goes over in to the negatives doing 0 dmg, and its semi permeant, only way to reset it is to relog in the world
![unknown](https://user-images.githubusercontent.com/85005207/120057602-8d8bf180-c044-11eb-8756-b0c3cd430b0d.png)

**Comment by Fargowilta** [comment]
wrong mod, thats dlc, but it might be fixed by now also
