### ISSUE TITLE
Error and crash when hovering mouse over Soul of Eternity

### ISSUE THREAD

**Issue by ABirdNamedSuki** [Fargowilta/Fargowiltas#48]
This bug report came while using the new tModLoader beta 64 bit version, so take it with a grain of salt.
The game crashed when hovering over the Soul of Eternity. Using cheat mods, you can hold it on your cursor after grabbing it from the cheat menu. You can even throw it with Overhaul physics and not have any issues. Only crashes for a mouse hover.

I took a peak at the log below, and it seems that the game does not like something about the tooltip once in a player's inventory.
`System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at FargowiltasSouls.Items.Accessories.Souls.EternitySoul.ModifyTooltips(List`1 tooltips) in FargowiltasSouls\Items\Accessories\Souls\EternitySoul.cs:line 464`

Below the log is my mod list. It is VERY LARGE, courtesy of tModLoader 64 bit expanded ram usage. I was using the Soul as a means to test out a potential new world, however, I was committing to another character with the same mod setup. I am about a week into that play-through, without many if not any crashes.

Let me know if there is any way I can help to fix the issue.

[client.log](https://github.com/Fargowilta/Fargowiltas/files/4301369/client.log)

[Super Overloaded modpack.txt](https://github.com/Fargowilta/Fargowiltas/files/4301372/Super.Overloaded.modpack.txt)

**Comment by Fargowilta** [comment]
Well I cannot replicate this so maybe it's fixed by now? (also technically wrong repo lul)

**Comment by ABirdNamedSuki** [comment]
Ok thanks anyway.
